### ISSUE TITLE
Problem Parsing some GTK Themes

### ISSUE THREAD

**Issue by Julian-Cremer-92** [jgmenu/jgmenu#183]
There is sometimes the Problem, HEX colors cannot be parsed by jgmenu-gtktheme.py.
Here my personal quick fix for the issue. However, the foreground color seems to still have problems.

``` python
from re import search

def rgb2hex(line):
    """ check if string is in rgb format otherwise treat as hex """
    if search("rgb", line):
        """ convert rgb values to a 6-digit hex string """
        s = line.split("rgb(")
        rgb = s[-1].replace(");", "").split(",")
        r = hex(int(rgb[0]))[2:]
        g = hex(int(rgb[1]))[2:]
        b = hex(int(rgb[2]))[2:]
        return "{}{}{}".format(fmt(r), fmt(g), fmt(b))
    else:
        return line.replace("#", "")
```

Hope, the code block in the comment helps.

**Comment by purpleleaf** [comment]
With Dracula gtk theme the fix doesn't work
```
Traceback (most recent call last):
  File "/usr/lib/jgmenu/jgmenu-gtktheme.py", line 111, in <module>
    main()
  File "/usr/lib/jgmenu/jgmenu-gtktheme.py", line 94, in main
    setconfig("color_sel_bg", rgb2hex(line))
                              ^^^^^^^^^^^^^
  File "/usr/lib/jgmenu/jgmenu-gtktheme.py", line 41, in rgb2hex
    r = hex(int(rgb[0]))[2:]
            ^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '@define-color theme_selected_bg_color rgba(189'
```

**Comment by johanmalm** [comment]
That python script needs to be improved :smile:

This is a much better version: https://github.com/labwc/labwc-gtktheme

Feel free to update it if you want / are able to. If not I'll have a go when I get a spare moment.
